import Head from "next/head";
import Feed from "../components/Feed";
import Navigation from "../components/Navigation";
import RightSection from "../components/RightSection";
import Storys from "../components/Storys";

export default function Home() {
  return (
    <div className="bg-slate-900">
      <Head>
        <title>Instagram | Dark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <Navigation />
        <div className="w-full h-[70px]"></div>
        <div className="max-w-[835px] min-h-screen mx-auto flex items-start justify-between">
          <div className="w-[470px] mx-auto">
            <Storys />
            <Feed />
          </div>
          <div className="w-[319px] hidden md:block ">
            <RightSection />
          </div>
        </div>
      </main>
    </div>
  );
}
